### ISSUE TITLE
Reading csv file produces ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Tapchicoma** [Kotlin/dataframe#101]
I am getting following exception on reading CSV file:
```
java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 10
        at org.apache.commons.csv.CSVRecord.get(CSVRecord.java:89)
        at org.jetbrains.kotlinx.dataframe.io.CsvKt.readDelim(csv.kt:292)
        at org.jetbrains.kotlinx.dataframe.io.CsvKt.readDelim(csv.kt:224)
        at org.jetbrains.kotlinx.dataframe.io.CsvKt.readCSV(csv.kt:111)
        at org.jetbrains.kotlinx.dataframe.io.CsvKt.readCSV$default(csv.kt:100)
```

CSV file content:
```csv
scenario,Spring server clean build,Spring server clean build,Spring client clean build,Spring client clean build,Ktor client clean build,Ktor client clean build,Incremental Spring server build with ABI change in FederatedSchemaGenerator,Incremental Spring server build with ABI change in FederatedSchemaGenerator,Incremental Spring client build with ABI change in GraphQLClient,Incremental Spring client build with ABI change in GraphQLClient
version,Gradle 7.4,Gradle 7.4,Gradle 7.4,Gradle 7.4,Gradle 7.4,Gradle 7.4,Gradle 7.4,Gradle 7.4,Gradle 7.4,Gradle 7.4
tasks,:graphql-kotlin-spring-server:assemble,:graphql-kotlin-spring-server:assemble,:graphql-kotlin-spring-client:assemble,:graphql-kotlin-spring-client:assemble,:graphql-kotlin-ktor-client:assemble,:graphql-kotlin-ktor-client:assemble,:graphql-kotlin-spring-server:assemble,:graphql-kotlin-spring-server:assemble,:graphql-kotlin-spring-server:assemble,:graphql-kotlin-spring-server:assemble
value,total execution time,task start,total execution time,task start,total execution time,task start,total execution time,task start,total execution time,task start
warm-up build #1,29872,1220,9190,1109,12037,1101,28652,7446,21952,7762
measured build #1,9214,496,2843,719,3206,546,1659,744,1014,739
measured build #2,8137,492,2286,501,2432,476,1341,604,841,602
measured build #3,7602,487,1896,467,2134,448,1335,568,801,587
warm-up build #5,,1802,455,2057,404,1183,510,780,588
warm-up build #6,,1592,391,2095,384,1346,549,738,563
measured build #1,,1729,407,1895,378,1291,630,680,516
measured build #2,,1831,527,1915,394,1047,451,667,505
measured build #3,,1901,422,1908,352,1010,436,710,525
measured build #4,,1577,391,1705,354,1050,455,668,481
measured build #5,,1428,344,1660,327,987,445,612,459
measured build #6,,1408,357,1619,303,1012,424,645,494
measured build #7,,1307,324,1691,337,906,392,607,445
measured build #8,,1288,337,1696,317,987,425,564,427
measured build #9,,1337,331,1589,307,916,400,566,429
measured build #10,,1246,286,1459,299,1038,484,640,492
```

kotlin-dataframe version: `0.8.0-rc-7`

**Comment by koperagen** [comment]
Thank you for the report!

**Comment by koperagen** [comment]
Library version `0.8.0-dev-952` is published. Gradle plugin will be available 2-3 hours later
