### ISSUE TITLE
Casting with verify=true gives vague exception

### ISSUE THREAD

**Issue by Jolanrensen** [Kotlin/dataframe#145]
```
Exception in thread "main" java.lang.IllegalArgumentException: Column `items` has type `org.jetbrains.kotlinx.dataframe.DataFrame<*>` that differs from target type `org.jetbrains.kotlinx.dataframe.DataFrame<*>`
	at org.jetbrains.kotlinx.dataframe.impl.api.ConvertToKt.convertToImpl$convertToSchema(convertTo.kt:70)
	at org.jetbrains.kotlinx.dataframe.impl.api.ConvertToKt.convertToImpl(convertTo.kt:121)
	at org.jetbrains.kotlinx.dataframe.impl.api.ConvertToKt.convertToImpl$default(convertTo.kt:45)
```
The exception occurs because `!allowConversion` but it doesn't help to see what's wrong. It can be reproduced by adding verify = true to the cast statement in the youtube intellij example.

**Comment by koperagen** [comment]
Fix in 0.9.0-dev-1118
