### ISSUE TITLE
Arrow Feather read from a Jupyter notebook fails with JPMS module access error

### ISSUE THREAD

**Issue by mikaelhg** [Kotlin/dataframe#148]
With a Docker container with 

```dockerfile
FROM jupyter/base-notebook:notebook-6.4.12

USER root

RUN apt-get update \
  && apt-get install -yq --no-install-recommends openjdk-18-jdk

USER $NB_UID

ENV JUPYTER_ENABLE_LAB=yes

RUN conda install -c jetbrains kotlin-jupyter-kernel
```

the Jupyter notebook cell execution

```kotlin
val df = DataFrame.readArrowFeather("foo.feather")
```

fails with 

<details>
  <summary>Stack trace collapsed, click me!</summary>
 
  ```
  null
  java.lang.ExceptionInInitializerError
	  at org.apache.arrow.memory.UnsafeAllocationManager.<clinit>(UnsafeAllocationManager.java:27)
	  at org.apache.arrow.memory.DefaultAllocationManagerFactory.<clinit>(DefaultAllocationManagerFactory.java:26)
	  at java.base/java.lang.Class.forName0(Native Method)
	  at java.base/java.lang.Class.forName(Class.java:383)
	  at java.base/java.lang.Class.forName(Class.java:376)
	  at org.apache.arrow.memory.DefaultAllocationManagerOption.getFactory(DefaultAllocationManagerOption.java:108)
	  at org.apache.arrow.memory.DefaultAllocationManagerOption.getDefaultAllocationManagerFactory(DefaultAllocationManagerOption.java:98)
	  at org.apache.arrow.memory.BaseAllocator$Config.getAllocationManagerFactory(BaseAllocator.java:733)
	  at org.apache.arrow.memory.ImmutableConfig.access$801(ImmutableConfig.java:24)
	  at org.apache.arrow.memory.ImmutableConfig$InitShim.getAllocationManagerFactory(ImmutableConfig.java:83)
	  at org.apache.arrow.memory.ImmutableConfig.<init>(ImmutableConfig.java:47)
	  at org.apache.arrow.memory.ImmutableConfig.<init>(ImmutableConfig.java:24)
	  at org.apache.arrow.memory.ImmutableConfig$Builder.build(ImmutableConfig.java:485)
	  at org.apache.arrow.memory.BaseAllocator.<clinit>(BaseAllocator.java:61)
	  at org.jetbrains.kotlinx.dataframe.io.Allocator$ROOT$2.invoke(arrow.kt:74)
	  at org.jetbrains.kotlinx.dataframe.io.Allocator$ROOT$2.invoke(arrow.kt:73)
	  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	  at org.jetbrains.kotlinx.dataframe.io.Allocator.getROOT(arrow.kt:73)
	  at org.jetbrains.kotlinx.dataframe.io.ArrowKt.readArrowFeather$default(arrow.kt:98)
	  at org.jetbrains.kotlinx.dataframe.io.ArrowKt.readArrowFeather(arrow.kt:245)
	  at org.jetbrains.kotlinx.dataframe.io.ArrowKt.readArrowFeather(arrow.kt:275)
	  at Line_4.<init>(Line_4.jupyter-kts:1)
	  at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	  at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	  at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	  at kotlin.script.experimental.jvm.BasicJvmScriptEvaluator.evalWithConfigAndOtherScriptsResults(BasicJvmScriptEvaluator.kt:105)
	  at kotlin.script.experimental.jvm.BasicJvmScriptEvaluator.invoke$suspendImpl(BasicJvmScriptEvaluator.kt:47)
	  at kotlin.script.experimental.jvm.BasicJvmScriptEvaluator.invoke(BasicJvmScriptEvaluator.kt)
	  at kotlin.script.experimental.jvm.BasicJvmReplEvaluator.eval(BasicJvmReplEvaluator.kt:49)
	  at org.jetbrains.kotlinx.jupyter.repl.impl.InternalEvaluatorImpl$eval$resultWithDiagnostics$1.invokeSuspend(InternalEvaluatorImpl.kt:103)
	  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	  at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	  at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	  at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	  at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	  at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	  at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	  at org.jetbrains.kotlinx.jupyter.repl.impl.InternalEvaluatorImpl.eval(InternalEvaluatorImpl.kt:103)
	  at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl$execute$1$result$1.invoke(CellExecutorImpl.kt:71)
	  at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl$execute$1$result$1.invoke(CellExecutorImpl.kt:69)
	  at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl.withHost(repl.kt:635)
	  at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute(CellExecutorImpl.kt:69)
	  at org.jetbrains.kotlinx.jupyter.repl.CellExecutor$DefaultImpls.execute$default(CellExecutor.kt:15)
	  at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl$evalEx$1.invoke(repl.kt:444)
	  at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl$evalEx$1.invoke(repl.kt:433)
	  at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl.withEvalContext(repl.kt:397)
	  at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl.evalEx(repl.kt:433)
	  at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl.eval(repl.kt:485)
	  at org.jetbrains.kotlinx.jupyter.messaging.ProtocolKt$shellMessagesHandler$2$res$1.invoke(protocol.kt:321)
	  at org.jetbrains.kotlinx.jupyter.messaging.ProtocolKt$shellMessagesHandler$2$res$1.invoke(protocol.kt:320)
	  at org.jetbrains.kotlinx.jupyter.JupyterExecutorImpl$runExecution$execThread$1.invoke(execution.kt:33)
	  at org.jetbrains.kotlinx.jupyter.JupyterExecutorImpl$runExecution$execThread$1.invoke(execution.kt:31)
	  at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
  Caused by: java.lang.RuntimeException: Failed to initialize MemoryUtil.
	  at org.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:136)
	  ... 54 more
  Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @4f5cfda5
	  at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	  at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	  at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
	  at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
	  at org.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:84)
	  ... 54 more
  ```

</details>

**Comment by koperagen** [comment]
Hi! Looks like https://arrow.apache.org/docs/java/install.html#java-compatibility

> When using Java 9 or later, some JDK internals must be exposed by adding --add-opens=java.base/java.nio=ALL-UNNAMED. Otherwise, you may see errors like module java.base does not "opens java.nio" to unnamed module.

**Comment by mikaelhg** [comment]
Solution:

``'dockerfile
ENV KOTLIN_JUPYTER_JAVA_OPTS="--add-opens=java.base/java.nio=ALL-UNNAMED"
```
