### ISSUE TITLE
a possible bug in DataFrame?

### ISSUE THREAD

**Issue by haksunlinm** [Kotlin/dataframe#243]
I have these two code snippets that are supposedly to do exactly the same thing.

However, using List, it gives this error:
dataframe number of values 1 not divisible by number of columns 2

Using array works fine.

//        List<BaseColumn> dataCols = new ArrayList<>(nCols);
        BaseColumn[] dataCols = new BaseColumn[nCols];
        for (int i = 0; i < nCols; ++i) {
//            dataCols.add( // TODO: a possible bug in DataFrame? Using list does not work
//                    newTypedDataCol(
//                            colNames.get(i),
//                            types.get(i),
//                            values.get(i)
//                    )

            dataCols[i] = newTypedDataCol( // using array works
                    colNames.get(i),
                    types.get(i),
                    values.get(i)
            );

**Comment by Jolanrensen** [comment]
Can you give a larger sample? The only thing I can see you do is adding an assumably typed column to an untyped list or array. This cannot cause that error. I assume the error is in your `newTypedDataCol()` function, which is not a part of Dataframe.
May I also ask why you are using Java for Dataframe? Dataframe is a Kotlin library that heavily relies on reified types, extension functions, lambdas, and Kotlin reflection. I would strongly advise against using it from Java unless you have no choice.

**Comment by koperagen** [comment]
Can you share a stacktrace for this error?

**Comment by haksunlinm** [comment]
Here we go. :)

Exception in thread "main" java.lang.IllegalArgumentException: Number of values 1 is not divisible by number of columns 2
	at org.jetbrains.kotlinx.dataframe.api.DataFrameBuilder.invoke1(constructors.kt:237)
	at org.jetbrains.kotlinx.dataframe.api.DataFrameBuilder.invoke(constructors.kt:229)
	at dev.nm.s2.data.db.DataFrameSupport.dataFrameFromResultSet(DataFrameSupport.java:81)
	at dev.nm.s2.data.db.DbAccess.lambda$dataFrame$2(DbAccess.java:73)
	at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:388)
	at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:266)
	at dev.nm.s2.data.db.DbAccess.load(DbAccess.java:78)
	at dev.nm.s2.data.db.DbAccess.dataFrame(DbAccess.java:73)
	at dev.nm.s2.data.db.command.DbTableCommand.dataFrame(DbTableCommand.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.nm.s2.data.DataCommand.invoke(DataCommand.java:114)
	at dev.nm.s2.data.DataCommand.dataFrame(DataCommand.java:99)
	at dev.nm.s2.data.Demo.dataFrames(Demo.java:108)
	at dev.nm.s2.data.Demo.main(Demo.java:43)
Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:982)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:929)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:457)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
------------------------------------------------------------------------

**Comment by koperagen** [comment]
Hm, how do you call `dataFrameOf` constructor? To create a dataframe from list of columns you need `dataFrameOf(dataCols)`, but from stack trace i suspect you're using something like `dataFrameOf(columnNames)(dataCols)`, no?

**Comment by Jolanrensen** [comment]
Okay, I would advise you to write the compatibility layer in Kotlin. Dataframe is not built with Java in mind, like, at all. Solving errors like this will only lead to more. If you write the compatibility layer in Kotlin you can just use the normal Dataframe API to create columns. However, you can make specific overloads for Java that don't rely on reflection.

**Comment by koperagen** [comment]
I see, try `ConstructorsKt.dataFrameOf(dataCols);` instead of `new DataFrameBuilder(colNames).invoke(dataCols)`

**Comment by haksunlinm** [comment]
ConstructorsKt.dataFrameOf(dataCols); won't compile. See screenshot below.

![wont_compile](https://user-images.githubusercontent.com/65719379/215680912-916cecda-04e9-40e9-9789-36837cb2074c.jpg)

This compiles and works.


        List<ValueColumn> dataCols = new ArrayList<>(nCols);
//        BaseColumn[] dataCols = new BaseColumn[nCols];
        for (int i = 0; i < nCols; ++i) {
            dataCols.add( // TODO: a possible bug in DataFrame? Using List does not work
                    newTypedDataCol(
                            colNames.get(i),
                            types.get(i),
                            values.get(i)
                    ));
            //            dataCols[i] = newTypedDataCol( // using array works
            //                    colNames.get(i),
            //                    types.get(i),
            //                    values.get(i)
            //            );
        }

//        return new DataFrameBuilder(colNames).invoke(dataCols);
//        return ConstructorsKt.dataFrameOf(dataCols);
        return ConstructorsKt.dataFrameOf(colNames, dataCols);



It is very unsettling.
ConstructorsKt.dataFrameOf(dataCols); should compile. I see the method in the jar file and it is public.

Also, List and Array should function exactly the same in this regard, but List does not work for 

return new DataFrameBuilder(colNames).invoke(dataCols);


So, there seems to be some more fundamental that I do not understand...



On second thought, it may be easier to write the interface in Kotlin altogether. We are just writing a layer to convert our legacy data structures to the new Kotlin data structure.

**Comment by Jolanrensen** [comment]
Alright, since we don't plan on supporting Dataframe from Java I'm closing it for now. Feel free to reopen if you need any help writing the compatibility layer in Kotlin!
