### ISSUE TITLE
NoSuchMethodError: [...] CSVFormat.withAllowDuplicateHeaderNames(boolean)

### ISSUE THREAD

**Issue by catacgc** [Kotlin/dataframe#399]
With these versions:

```
- java --version
openjdk 19.0.2 2023-01-17

- Python 3.11.0

- jupyter-lab --version
4.0.2
```

And this notebook:

```
%use lets-plot, krangl, dataframe
val df = DataFrame.readCSV("/some/path.csv")
```

I get the following exception:

```
'org.apache.commons.csv.CSVFormat org.apache.commons.csv.CSVFormat.withAllowDuplicateHeaderNames(boolean)'
java.lang.NoSuchMethodError: 'org.apache.commons.csv.CSVFormat org.apache.commons.csv.CSVFormat.withAllowDuplicateHeaderNames(boolean)'
	at org.jetbrains.kotlinx.dataframe.io.CsvKt.getFormat(csv.kt:203)
	at org.jetbrains.kotlinx.dataframe.io.CsvKt.readDelim(csv.kt:225)
	at org.jetbrains.kotlinx.dataframe.io.CsvKt$readCSV$1.invoke(csv.kt:109)
	at org.jetbrains.kotlinx.dataframe.io.CsvKt$readCSV$1.invoke(csv.kt:108)
	at org.jetbrains.kotlinx.dataframe.io.CommonKt.catchHttpResponse(common.kt:15)
	at org.jetbrains.kotlinx.dataframe.io.CsvKt.readCSV(csv.kt:108)
	at org.jetbrains.kotlinx.dataframe.io.CsvKt.readCSV$default(csv.kt:97)
	at Line_17_jupyter.<init>(Line_17.jupyter.kts:1)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at kotlin.script.experimental.jvm.BasicJvmScriptEvaluator.evalWithConfigAndOtherScriptsResults(BasicJvmScriptEvaluator.kt:105)
	at kotlin.script.experimental.jvm.BasicJvmScriptEvaluator.invoke$suspendImpl(BasicJvmScriptEvaluator.kt:47)
	at kotlin.script.experimental.jvm.BasicJvmScriptEvaluator.invoke(BasicJvmScriptEvaluator.kt)
	at kotlin.script.experimental.jvm.BasicJvmReplEvaluator.eval(BasicJvmReplEvaluator.kt:49)
	at org.jetbrains.kotlinx.jupyter.repl.impl.InternalEvaluatorImpl$eval$resultWithDiagnostics$1.invokeSuspend(InternalEvaluatorImpl.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.jetbrains.kotlinx.jupyter.repl.impl.InternalEvaluatorImpl.eval(InternalEvaluatorImpl.kt:103)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl$execute$1$result$1.invoke(CellExecutorImpl.kt:75)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl$execute$1$result$1.invoke(CellExecutorImpl.kt:73)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl.withHost(repl.kt:666)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute(CellExecutorImpl.kt:73)
	at org.jetbrains.kotlinx.jupyter.repl.CellExecutor$DefaultImpls.execute$default(CellExecutor.kt:15)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl$evalEx$1.invoke(repl.kt:479)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl$evalEx$1.invoke(repl.kt:470)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl.withEvalContext(repl.kt:433)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl.evalEx(repl.kt:470)
	at org.jetbrains.kotlinx.jupyter.messaging.ProtocolKt$shellMessagesHandler$2$res$1.invoke(protocol.kt:318)
	at org.jetbrains.kotlinx.jupyter.messaging.ProtocolKt$shellMessagesHandler$2$res$1.invoke(protocol.kt:312)
	at org.jetbrains.kotlinx.jupyter.JupyterExecutorImpl$runExecution$execThread$1.invoke(execution.kt:37)
	at org.jetbrains.kotlinx.jupyter.JupyterExecutorImpl$runExecution$execThread$1.invoke(execution.kt:32)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

**Comment by Jolanrensen** [comment]
Does the same exception appear when you just %use dataframe and not the other libraries?

**Comment by catacgc** [comment]
Nope, that was it: if I remove `krangl`, then it works

**Comment by catacgc** [comment]
Spoke to soon (was executing a cached cell), still fails with the following code:

```
%use dataframe
val df = DataFrame.readCSV("/some/path.csv")
```

**Comment by catacgc** [comment]
So, here's the thing, I cannot reproduce, but I believe the problem lies with using two separate notebooks with the same notebook server. One of them used the krangl, the other used dataframe and they clash. 

I'll close it for now, because if I start fresh, I cannot reproduce it
