### ISSUE TITLE
Test `writeJsonStr` is broken and probably is not a part of common suite

### ISSUE THREAD

**Issue by zaleslaw** [Kotlin/dataframe#752]
```

"[
    {
        "name": {
            "firstName": "Alice",
            "lastName": "Cooper"
        },
        "age": 15,
        "city": "London",
        "weight": 54,
        "isHappy": true
    },
    {
        "name": {
            "firstName": "Bob",
            "lastName": "Dylan"
        },
        "age": 45,
        "city": "Dubai",
        "weight": 87,
        "isHappy": true
    },
    {
        "name": {
            "firstName": "Charlie",
            "lastName": "Daniels"
        },
        "age": 20,
        "city": "Moscow",
        "weight": null,
        "isHappy": false
    },
    {
        "name": {
            "firstName": "Charlie",
            "lastName": "Chaplin"
        },
        "age": 40,
        "city": "Milan",
        "weight": null,
        "isHappy": true
    },
    {
        "name": {
            "firstName": "Bob",
            "lastName": "Marley"
        },
        "age": 30,
        "city": "Tokyo",
        "weight": 68,
        "isHappy": true
    },
    {
        "name": {
            "firstName": "Alice",
            "lastName": "Wolf"
        },
        "age": 20,
        "city": null,
        "weight": 55,
        "isHappy": false
    },
    {
        "name": {
            "firstName": "Charlie",
            "lastName": "Byrd"
        },
        "age": 30,
        "city": "Moscow",
        "weight": 90,
        "isHappy": true
    }
]" should start with "[
    {
        "name": {
            "firstName": "Alice",
            "lastName": "Cooper"
        },
        "age": 15,
        "city": "London",
        "weight": 54,
        "isHappy": true" (diverged at index 1)
java.lang.AssertionError: "[
    {
        "name": {
            "firstName": "Alice",
            "lastName": "Cooper"
        },
        "age": 15,
        "city": "London",
        "weight": 54,
        "isHappy": true
    },
    {
        "name": {
            "firstName": "Bob",
            "lastName": "Dylan"
        },
        "age": 45,
        "city": "Dubai",
        "weight": 87,
        "isHappy": true
    },
    {
        "name": {
            "firstName": "Charlie",
            "lastName": "Daniels"
        },
        "age": 20,
        "city": "Moscow",
        "weight": null,
        "isHappy": false
    },
    {
        "name": {
            "firstName": "Charlie",
            "lastName": "Chaplin"
        },
        "age": 40,
        "city": "Milan",
        "weight": null,
        "isHappy": true
    },
    {
        "name": {
            "firstName": "Bob",
            "lastName": "Marley"
        },
        "age": 30,
        "city": "Tokyo",
        "weight": 68,
        "isHappy": true
    },
    {
        "name": {
            "firstName": "Alice",
            "lastName": "Wolf"
        },
        "age": 20,
        "city": null,
        "weight": 55,
        "isHappy": false
    },
    {
        "name": {
            "firstName": "Charlie",
            "lastName": "Byrd"
        },
        "age": 30,
        "city": "Moscow",
        "weight": 90,
        "isHappy": true
    }
]" should start with "[
    {
        "name": {
            "firstName": "Alice",
            "lastName": "Cooper"
        },
        "age": 15,
        "city": "London",
        "weight": 54,
        "isHappy": true" (diverged at index 1)
	at org.jetbrains.kotlinx.dataframe.samples.api.Write.writeJsonStr(Write.kt:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

**Comment by Jolanrensen** [comment]
I suspect it's OS dependent thanks to the `rejoinWithSystemLineSeparator()` call
