### ISSUE TITLE
Support for KSP2 (for beta K2 compiler exploration)

### ISSUE THREAD

**Issue by laurentperez** [Kotlin/dataframe#770]
Hi

Upgrading from K1 compiler `1.9.23` to K2 `id 'org.jetbrains.kotlin.jvm' version "2.0.0"`, a project using Kotlin dataframe id `"org.jetbrains.kotlinx.dataframe" version "0.13.1"` does not compile anymore

This is related to a java.lang.NoSuchMethodError in KSP when the project is upgraded from K1 to K2. This may be similar to https://youtrack.jetbrains.com/issue/KT-68732/Kotlin-Multiplatform-Gradle-Sync-Issue-Latest-Stable-of-Multiplatform-Plugin-2.0.0

Per https://github.com/google/ksp/releases users are "encouraged" to try out KSP2. 

Are Kotlin dataframes expected to support K2/KSP2 ? or should I stick to a specific K1 1.x.x compiler for now ?

thanks

Stacktrace is

```
What went wrong:
Execution failed for task ':dataviz:kspKotlin'.
> 'org.jetbrains.kotlin.incremental.ChangedFiles com.google.devtools.ksp.gradle.KspTaskJvm.getChangedFiles(org.gradle.work.InputChanges, java.util.List)'
Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dataviz:kspKotlin'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:148)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
   (...)
org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.incremental.ChangedFiles com.google.devtools.ksp.gradle.KspTaskJvm.getChangedFiles(org.gradle.work.InputChanges, java.util.List)'
        at com.google.devtools.ksp.gradle.KspTaskJvm.callCompilerAsync$kotlin_gradle_plugin_common(KotlinFactories.kt:222)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompilerAsync$kotlin_gradle_plugin_common(KotlinCompile.kt:55)
        at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.executeImpl(AbstractKotlinCompile.kt:310)



```

**Comment by Jolanrensen** [comment]
Hi @laurentperez! Could you try this temporary fix https://github.com/Kotlin/dataframe/issues/649#issuecomment-2172962193? It will allow you to have your own KSP version independent of DataFrame's provided KSP version.
This is only temporary of course :) We're almost ready to update the library to Kotlin 2.0 too, then this won't be necessary anymore.

**Comment by Jolanrensen** [comment]
The next release (0.14.0) will be based on 2.0 so the problem should be fixed. In the meantime, you could try it with the latest dev version https://central.sonatype.com/artifact/org.jetbrains.kotlinx/dataframe?smo=true
