### ISSUE TITLE
Offer an argument for `writeExcel()` to remove the limitation of cell's text max length

### ISSUE THREAD

**Issue by DrEden33773** [Kotlin/dataframe#830]
# Offer an arg for `writeExcel()` to remove the limitation of cell's text max length

## Brief description of the issue

Here's the code:

```kotlin
import kotlinx.coroutines.*
import java.io.File
import org.jetbrains.kotlinx.dataframe.DataFrame
import org.jetbrains.kotlinx.dataframe.io.readCSV

val csvDf = DataFrame.readCSV("data.csv")

fun main() = runBlocking {
    // disableAllCellLengthLimit()
    if (File("data.csv").exists()) {
        csvDf.writeExcel(File("data.xlsx"))
        return@runBlocking
    }
    // ...
}
```

In this case, content in `data.csv`'s cell could be huge (more than `32767` characters), so you'll get an exception
below:

```txt
Exception in thread "main" java.lang.IllegalArgumentException: The maximum length of cell contents (text) is 32767 characters
	at org.apache.poi.ss.usermodel.CellBase.checkLength(CellBase.java:292)
	at org.apache.poi.ss.usermodel.CellBase.setCellValue(CellBase.java:273)
	at org.jetbrains.kotlinx.dataframe.io.XlsxKt.setCellValueByGuessedType(xlsx.kt:471)
	at org.jetbrains.kotlinx.dataframe.io.XlsxKt.writeExcel(xlsx.kt:396)
	at org.jetbrains.kotlinx.dataframe.io.XlsxKt.writeExcel(xlsx.kt:351)
	at org.jetbrains.kotlinx.dataframe.io.XlsxKt.writeExcel(xlsx.kt:339)
	at org.jetbrains.kotlinx.dataframe.io.XlsxKt.writeExcel$default(xlsx.kt:318)
	at eden.ExcelBuilderKt.buildExcel(ExcelBuilder.kt:15)
	at eden.MainKt$main$1.invokeSuspend(Main.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:47)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at eden.MainKt.main(Main.kt:18)
	at eden.MainKt.main(Main.kt)
```

That's because `kotlinx-dataframe`'s `writeExcel` method uses `Apache POI` (org.apache.poi.ss.usermodel.CellBase)

It will automatically call `checkLength` method:

```java
private void checkLength(String value) {
    if (value.length() > getSpreadsheetVersion().getMaxTextLength()) {
        final String message = String.format(Locale.ROOT,
                "The maximum length of cell contents (text) is %d characters",
                getSpreadsheetVersion().getMaxTextLength());
        throw new IllegalArgumentException(message);
    }
}
```

`getSpreadsheetVersion()` only has two values: `EXCEL97` and `EXCEL2007`

```java
public enum SpreadsheetVersion {
    EXCEL97(0x10000, 0x0100, 30, 3, 4000, 32767),
    EXCEL2007(0x100000, 0x4000, 255, Integer.MAX_VALUE, 64000, 32767);
    private final int _maxRows;
    private final int _maxColumns;
    private final int _maxFunctionArgs;
    private final int _maxCondFormats;
    private final int _maxCellStyles;
    private final int _maxTextLength;
}
```

Unfortunately, the `maxTextLength` is `32767` for both `EXCEL97` and `EXCEL2007`

## Solution

A practical solution (at least that's what I've done) could be:

```txt
Disable the limitation of cell's text max length (via reflection)
```

Here's the code:

```kotlin
import kotlinx.coroutines.*
import org.apache.poi.ss.SpreadsheetVersion

fun disableCellLengthLimitOf(spreadsheetVersion: SpreadsheetVersion) {
    println("---> Disabling cell length limit of ${spreadsheetVersion.name} <---")
    val maxTextLength = spreadsheetVersion.javaClass.getDeclaredField("_maxTextLength")
    maxTextLength.isAccessible = true
    maxTextLength.set(spreadsheetVersion, Int.MAX_VALUE)
}

fun disableAllCellLengthLimit() {
    disableCellLengthLimitOf(SpreadsheetVersion.EXCEL97)
    disableCellLengthLimitOf(SpreadsheetVersion.EXCEL2007)
}

fun main() = runBlocking {
    disableAllCellLengthLimit() // call this at the beginning
    // ...
}
```

## Suggestion

Offer an `optional argument` for `org.jetbrains.kotlinx.dataframe.DataFrame<T>.writeExcel`

It could be `maxTextLength: Int = Int.MAX_VALUE` (default value is `Int.MAX_VALUE` or `32767`)

Then, use the param to adjust `maxTextLength` in a `cell` (use `reflection` or anything else)

**Comment by DrEden33773** [comment]
Here's my `pull request` to solve the issue: #838

**Comment by Jolanrensen** [comment]
While I can see your solution would work to increase the cell size, I keep wondering whether we should. The `maxTextLength` from Apache is there for a reason I assume. Are the Excel files still readable when we cross that boundary? ([According to Microsoft this is a hard limit](https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3))
And if they are readable and this is a new Excel format, shouldn't this be better solved on their side instead of with reflection on our side?

**Comment by DrEden33773** [comment]
Agree, I've forgotten to look up Microsoft's regulation of excel format.

**Comment by Jolanrensen** [comment]
I did find Google Sheets has a limit of 50k characters per cell. However, for this case I think it's still best to let Apache create a Sheets format or something similar.

**Comment by DrEden33773** [comment]
Yeah, that's a much better solution.

**Comment by Jolanrensen** [comment]
I'll close it for now, until we might need it again in the future :)
