### ISSUE TITLE
Dataframe with PostgreSQL: Class declares 1 type parameters, but 0 were provided.

### ISSUE THREAD

**Issue by don41382** [Kotlin/dataframe#859]
Plugin-Version: 241.18034.95

First of all: Thanks for the brilliant project! I just had to get started, but ran directly into an issue: When I read a table of a Postgresql Database using`readSqlTable` with a column of the type `integer[]`, I'll get the error `Class declares 1 type parameters, but 0 were provided.`.

## Code
```kotlin
USE {
    dependencies("org.postgresql:postgresql:42.7.3")
}

%use dataframe
import java.sql.DriverManager
import java.util.*

val dbConfig = DatabaseConfiguration(url = "jdbc:postgresql://localhost:5499/demo", user = "username", password = "password")

val table = DataFrame.readSqlTable(dbConfig = dbConfig, "example")
```

## DDL
```sql
CREATE TABLE example (
    names integer[]
);
```

## Stacktrace
```
Class declares 1 type parameters, but 0 were provided.
java.lang.IllegalArgumentException: Class declares 1 type parameters, but 0 were provided.
	at kotlin.reflect.full.KClassifiers.createType(KClassifiers.kt:53)
	at kotlin.reflect.full.KClassifiers.createType$default(KClassifiers.kt:42)
	at org.jetbrains.kotlinx.dataframe.io.ReadJdbcKt.makeCommonSqlToKTypeMapping(readJdbc.kt:688)
	at org.jetbrains.kotlinx.dataframe.io.ReadJdbcKt.generateKType(readJdbc.kt:635)
	at org.jetbrains.kotlinx.dataframe.io.ReadJdbcKt.fetchAndConvertDataFromResultSet(readJdbc.kt:576)
	at org.jetbrains.kotlinx.dataframe.io.ReadJdbcKt.readSqlTable(readJdbc.kt:148)
	at org.jetbrains.kotlinx.dataframe.io.ReadJdbcKt.readSqlTable(readJdbc.kt:116)
	at org.jetbrains.kotlinx.dataframe.io.ReadJdbcKt.readSqlTable$default(readJdbc.kt:110)
	at Line_38_jupyter.<init>(Line_38.jupyter.kts:1)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
```

**Comment by zaleslaw** [comment]
Thanks for reporting! It‘s a bug!

**Comment by don41382** [comment]
Thanks for the quick fix!
